// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayFeatures
{
        public const string achievement_junk_hater = "CgkI5aKAst0KEAIQBQ"; // <GPGSID>
        public const string achievement_christopher_spacelumbus = "CgkI5aKAst0KEAIQAQ"; // <GPGSID>
        public const string achievement_interstellar_perfection = "CgkI5aKAst0KEAIQAg"; // <GPGSID>
        public const string achievement_close_call = "CgkI5aKAst0KEAIQBA"; // <GPGSID>
        public const string achievement_panspermia = "CgkI5aKAst0KEAIQAw"; // <GPGSID>
        public const string leaderboard_space_pioneers = "CgkI5aKAst0KEAIQBg"; // <GPGSID>

}

