// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class 
{
        public const string achievement_spinaroonie = "CgkI5tG9p7UVEAIQBg"; // <GPGSID>
        public const string achievement_christopher_colombus_reincarnate = "CgkI5tG9p7UVEAIQAw"; // <GPGSID>
        public const string leaderboard_space_explorers_galore = "CgkI5tG9p7UVEAIQBw"; // <GPGSID>
        public const string achievement_untouchable = "CgkI5tG9p7UVEAIQAQ"; // <GPGSID>
        public const string achievement_asteroid_invasion_survivor = "CgkI5tG9p7UVEAIQAg"; // <GPGSID>
        public const string achievement_master_of_the_space_continium = "CgkI5tG9p7UVEAIQBQ"; // <GPGSID>
        public const string achievement_were_not_alone = "CgkI5tG9p7UVEAIQBA"; // <GPGSID>

}

